#version 450

// 워크그룹 사이즈 세팅
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

// ==========================================
// 1. 데이터 구조체 정의
// ==========================================
struct PhysicsVertex {
    vec3 pos;       // 현재 Newton 위치 (x_k)
    float invMass;
    vec3 vel;       // 현재 Newton 속도 (v_k)
    float padding;
    vec4 normal;
};

// ==========================================
// 2. 버퍼 바인딩
// ==========================================
layout(std430, binding = 0) buffer PhysicsIn { PhysicsVertex physData[]; };
layout(binding = 3) buffer ForceBuffer   { vec4 forces[]; };

layout(push_constant) uniform PushConstants {
    float dt;
    float u_Time;
    uint numWorkGroupsFromPreviousPass;
    float youngsModulus;
    float poissonsRatio;
    uint colorOffset;
    uint colorCount;
} pc;

void main() {
    uint idx = gl_GlobalInvocationID.x;

    if (idx < physData.length()) {
        float invM = physData[idx].invMass;

        if (invM > 0.0) {
            vec3 f = forces[idx].xyz;
            vec3 gravity = vec3(0.0, -9.8, 0.0);

            vec3 totalForce = f + gravity / invM;

            vec3 v = physData[idx].vel;
            vec3 p = physData[idx].pos;
            
            //v *= pow(damping, 1.0 / float(pc.subStepCnt));
            float dampingCoefficient = 2.0;
            float damping = exp(-dampingCoefficient * pc.dt);
            v *= damping;

            float sdt = pc.dt;

            v += totalForce * invM * sdt;
            p += v * sdt;
            
            if (p.y < -1.5) {
                p = physData[idx].pos; // 바닥 충돌 시 위치를 이전 위치로 되돌림
            }

            v = (p - physData[idx].pos) / sdt;

            physData[idx].pos = p;
            physData[idx].vel = v;
        }
    }
}